### ISSUE TITLE
Update the workflow to build the integration tests

### ISSUE THREAD

**Issue by antoniyatrifonova** [eclipse-kanto/local-digital-twins#23]
The integration tests are separated from the unit tests by using the golang build tag. As a result the workflow builds and runs only the integration test. It is need to update this workflow to build also integration tests.

**Comment by daniel-milchev** [comment]
I'll have a look at this.

**Comment by k-gostev** [comment]
The build workflow must include `integration_hub` tag for the all `it_*` files for all packages as well as the the `integration` tag that will be added later on. The `integration` directory could be used for all builds.
